name: flower_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: ^3.0.1
  pull_to_refresh_flutter3: ^2.0.1
  scrollable_positioned_list: ^0.3.2
  flutter_svg: ^1.1.3
  cached_network_image: ^3.2.1
  flutter_easyloading: ^3.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
